### ISSUE TITLE
Require a namespace when creating a chat

### ISSUE THREAD

**Issue by skks1212** [coronasafe/ayushma#26]
Currently, we require a `namespace` value in the incoming data at the `/converse` endpoint. Remove this requirement and add it to the `/chats` POST endpoint. (you can update the serializer). Update the `Chat` model to store the namespace value. Now, in the `/converse` endpoint, fetch the namespace from the Chat object.

**Comment by skks1212** [comment]
@ishanExtreme Did you get to work on this?

**Comment by ishanExtreme** [comment]
on it @skks1212
