### ISSUE TITLE
Compatibility Issue with OpenAI Whisper Implementation in openai>=1.0.0

### ISSUE THREAD

**Issue by Ashesh3** [coronasafe/ayushma#429]
We are facing a compatibility issue with our OpenAI Whisper implementation. The current codebase attempts to use `openai.Audio`, which is no longer supported in the latest OpenAI Python library version (`openai>=1.0.0`).

### Error Message:
```
You tried to access openai.Audio, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API. You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`
```

### Proposed Solutions:
1. **Automatic Codebase Upgrade:** Run `openai migrate` to automatically update our codebase to be compatible with the `openai>=1.0.0` interface.
   
A detailed migration guide is available here: [OpenAI Python Migration Guide](https://github.com/openai/openai-python/discussions/742).

### Action Items:
- [ ] Review the [migration guide](https://github.com/openai/openai-python/discussions/742) and assess the scope of changes required for our codebase.
- [ ] Implement the chosen solution and thoroughly test to ensure that our OpenAI Whisper implementation works seamlessly with the updated library.

**Comment by Ashesh3** [comment]
@ishanExtreme you mentioned that you were working on a fix for this issue, what's the status of the fix?

**Comment by ishanExtreme** [comment]
Expected to fix it by today...

**Comment by ishanExtreme** [comment]
> @ishanExtreme you mentioned that you were working on a fix for this issue, what's the status of the fix?


Expected to fix it by today...
