### ISSUE TITLE
Allow users to upsert web links and direct text (through endpoint)

### ISSUE THREAD

**Issue by skks1212** [coronasafe/ayushma#62]
Currently we are only processing pdf and txt files. Diversify this to take up web links and direct text. Alter the models to store this data as well.

**Comment by ishanExtreme** [comment]
@skks1212 What is meant by web links? Are we going change the upsert function to process direct text and scrape website from the given link? Can you explain user the flow for this issue

**Comment by skks1212** [comment]
@ishanExtreme Yes, you will have to scrape from the URL.

For ex. If we want to scrape data from React docs, we can do that by entering the URL of the page, one page at a time (maybe we can automate that at a later stage)

**Comment by skks1212** [comment]
Direct text is a different thing, where we can just enter text directly to a textarea and upsert
