### ISSUE TITLE
Ayushma: Add Feedback

### ISSUE THREAD

**Issue by skks1212** [coronasafe/ayushma#75]
Users should be able to provide feedback to the chat. 
This should be handled by a `Feedback` model, which has

- chat_message : fk to `ChatMessage`
- user : fk to `User`
- liked : boolean
- message : (optional) text

Make relevant views and serializers. Feedback should be listed with `/feedback` url, with possible filters -
- project_id
- chat_id
- chat_message_id
- liked

Only admins should be able to list and retrieve all feedback. Normal users can only list their own. Feedbacks cannot be deleted.

**Comment by khavinshankar** [comment]
Hey @skks1212, I have a couple of questions,
1. In the above description, you mentioned adding `user_id` as a foreign key, but as the chat itself is user-specific, do we need that? :thinking:
![image](https://github.com/coronasafe/ayushma/assets/29787772/0d821070-09af-4c15-a1de-f1fb5f9acdf4)

2. Second is more like clarification, we should also have thumbs down, right? And as far as storing value goes, liked === null, no feedback; liked === true, thumbs up; and liked === false, thumbs down;

**Comment by skks1212** [comment]
Hey @khavinshankar yes we can leave out the user field. 
And as liked is Boolean, thumbs-up will be ===true and thumbs down will be ===false. It will be a not null field

**Comment by khavinshankar** [comment]
Hey @skks1212, about `/feedback` endpoint, is just an endpoint enough or do we need a dedicated screen in the frontend, if so where?

**Comment by skks1212** [comment]
@khavinshankar we need the feedback buttons on the chat UI (👍,👎) and a way to list feedbacks in the admin panel, preferably in its own page
